### ISSUE TITLE
Res folder conflict in manifest

### ISSUE THREAD

**Issue by wlTrunks** [awxkee/avif-coder-coil#1]
Please remove res folder avifcoillibrary with icons, and clean manifest with application tag?
    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/Theme.AvifCoil" />

**Comment by wlTrunks** [comment]
Also repository closed to make any PR, maybe i can provide fix for it
thank you

**Comment by awxkee** [comment]
Try '1.5.3.1'. Project has default github PR settings, you may easily do PR via forking
