### ISSUE TITLE
Does this support transparency?

### ISSUE THREAD

**Issue by firefinchdev** [awxkee/avif-coder-coil#10]
Using coil 3.x with avif-coder-coil (2.0.10)
While trying to render this image (download link: https://easyupload.io/9uf5za), black area is visible where transparency is there.

**Comment by awxkee** [comment]
Plugin handles that image correctly.
If you see the black area that means it was handled by coil itself and plugin is not configured

**Comment by firefinchdev** [comment]
Sorry, initially created there, but then found this repo, so thought that creating issue here would be better.
Anyways, it worked perfectly after providing `.bitmapConfig(Bitmap.Config.ARGB_8888)` (as done in sample app).

Closing the issue.
Thanks.
