### ISSUE TITLE
Support for minSdk 21

### ISSUE THREAD

**Issue by firefinchdev** [awxkee/avif-coder-coil#11]
Hi,
Would it be feasible to support SDK levels 21 - 23?

**Comment by firefinchdev** [comment]
oh ok. thanks for the quick update.
@awxkee pls help me clarify one thing: glide's avif integration library uses https://github.com/AOMediaCodec/libavif to load avif, while your library uses your own coder library.

is there any advantage (or supported features, etc) that your coder lib provides, that ao media's lib is missing?

**Comment by awxkee** [comment]
My library also uses libavif, libavif itself is not a codec, only a avif file format parser. Glide libavif integration uses libgav1 for decoding, my integration libdav1d. libdav1d is the fastest AV1 decoder. My integration uses very fast YUV decoder, where glide integration uses slow YUV decoder. Also in my implementation ICC profiles and HDR images are supported, in glide implementation it is not.
