### ISSUE TITLE
avif sequence image (animated avif) support

### ISSUE THREAD

**Issue by gaond** [awxkee/avif-coder-coil#2]
Hello. It's a great and really awesome work.
I'm wondering if there are any plans to incorporate support for animated AVIF.

Actually, I noticed that [the libavif repository's JNI includes that functionality](https://github.com/AOMediaCodec/libavif/blob/main/android_jni/avifandroidjni/src/main/jni/libavif_jni.cc#L374-L379). However, I'm not entirely sure how to integrate it with your project.

Thank you.

**Comment by awxkee** [comment]
Hi.

Glad to hear you have an interest in project!

At the moment library totally depends on libheif, and libheif do not support animated sequences as my best knowledge.
To separate decoding/encoding functionality from libheif to libavif for avif and keep heic images there is significant rework is required.
Also there are no exists a proper `AnimatedDrawable` ( with caching, prefetching, memory using cutoff ) in android ecosystem so write one is also needed.

I consider very low spreading of avif sequences.

So in resolution at the moment I do not have any plans to support avifs.

If avifs is important for you it might be easier to implement your own decoder for coil based on libavif provided JNI.
It will be slower, do not support some features ( PQ, HLG ) some ICC profiles as well however it will work.
Also your implementation of `good` AnimatedDrawable still will be requirement.

**Comment by awxkee** [comment]
And without whole rework there are no sense just to add libavif to project, library does a lot of things to do a good rendering where libavif JNI provides just a basic support.

**Comment by gaond** [comment]
Thank you for your response.
I might have been looking for the Android library of [your other library](https://github.com/awxkee/avif.swift). With my limited knowledge, I'm not quite sure what functionalities should be added to the AnimatedDrawable. 
I'll close the issue. Thank you again.
